### ISSUE TITLE
Error starting a native image

### ISSUE THREAD

**Issue by sdelamo** [micronaut-guides/micronaut-security-jwt#10]
```
% sdk use java 20.1.0.r11-grl

Using java version 20.1.0.r11-grl in this shell.
sdelamo@Sergios-iMac-Pro complete % ./gradlew clean

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 845ms
1 actionable task: 1 executed
sdelamo@Sergios-iMac-Pro complete % ./gradlew assemble


> Task :compileJava
Note: Writing native-image.properties file to destination: META-INF/native-image/example/micronaut/native-image.properties
Note: Writing reflection-config.json file to destination: META-INF/native-image/example/micronaut/reflection-config.json
Note: Writing resource-config.json file to destination: META-INF/native-image/example/micronaut/resource-config.json
Note: Creating bean classes for 5 type elements

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 7s
10 actionable tasks: 10 executed
sdelamo@Sergios-iMac-Pro complete % native-image --no-server -cp build/libs/complete-0.1-all.jar
[micronautguide:54737]    classlist:   3,813.99 ms,  0.96 GB
[micronautguide:54737]        (cap):   2,341.58 ms,  0.96 GB
WARNING: Could not resolve io.netty.channel.epoll.EpollChannelOption for reflection configuration.
WARNING: Could not resolve io.netty.channel.kqueue.KQueueChannelOption for reflection configuration.
[micronautguide:54737]        setup:   3,385.39 ms,  0.96 GB
WARNING GR-10238: VarHandle for static field is currently not fully supported. Static field private static volatile java.lang.System$Logger jdk.internal.event.EventHelper.securityLogger is not properly marked for Unsafe access!
[micronautguide:54737]     (clinit):   1,850.43 ms,  4.56 GB
[micronautguide:54737]   (typeflow):  21,230.27 ms,  4.56 GB
[micronautguide:54737]    (objects):  32,676.40 ms,  4.56 GB
[micronautguide:54737]   (features):   3,154.66 ms,  4.56 GB
[micronautguide:54737]     analysis:  62,005.77 ms,  4.56 GB
[micronautguide:54737]     universe:   1,752.61 ms,  4.56 GB
[micronautguide:54737]      (parse):   5,227.56 ms,  4.63 GB
[micronautguide:54737]     (inline):   6,108.65 ms,  5.74 GB
[micronautguide:54737]    (compile):  18,567.81 ms,  5.62 GB
[micronautguide:54737]      compile:  33,219.08 ms,  5.62 GB
[micronautguide:54737]        image:   6,331.36 ms,  5.64 GB
[micronautguide:54737]        write:   1,872.89 ms,  5.64 GB
[micronautguide:54737]      [total]: 112,589.49 ms,  5.64 GB
sdelamo@Sergios-iMac-Pro complete % ./micronautguide -Xmx68m                                    
11:44:03.183 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
11:44:04.188 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
org.h2.jdbc.JdbcSQLSyntaxErrorException: (Message 90086 not found) [90086-199]
	at org.h2.util.JdbcUtils.loadUserClass(JdbcUtils.java:198)
	at org.h2.engine.Database.getTableEngine(Database.java:3172)
	at org.h2.schema.Schema.createTable(Schema.java:706)
	at org.h2.engine.Database.open(Database.java:824)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:35)
	at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:66)
	at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:143)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1858)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2595)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2581)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2133)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1508)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2728)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:227)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:294)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:280)
	at example.micronaut.Application.main(Application.java:8)
Caused by: java.lang.ClassNotFoundException: org.h2.mvstore.db.MVTableEngine
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.Class.forName(DynamicHub.java:1194)
	at org.h2.util.JdbcUtils.loadUserClass(JdbcUtils.java:191)
	... 38 common frames omitted
11:44:04.188 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type [javax.sql.DataSource]: Failed to initialize pool: (Message 90086 not found) [90086-199]
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type [javax.sql.DataSource]: Failed to initialize pool: (Message 90086 not found) [90086-199]
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1510)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2728)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:227)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:294)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:280)
	at example.micronaut.Application.main(Application.java:8)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [javax.sql.DataSource]: Failed to initialize pool: (Message 90086 not found) [90086-199]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1886)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2595)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2581)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2133)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1508)
	... 8 common frames omitted
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: (Message 90086 not found) [90086-199]
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:595)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:581)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:35)
	at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:66)
	at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:143)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1858)
	... 12 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: (Message 90086 not found) [90086-199]
	at org.h2.util.JdbcUtils.loadUserClass(JdbcUtils.java:198)
	at org.h2.engine.Database.getTableEngine(Database.java:3172)
	at org.h2.schema.Schema.createTable(Schema.java:706)
	at org.h2.engine.Database.open(Database.java:824)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	... 19 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.h2.mvstore.db.MVTableEngine
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.Class.forName(DynamicHub.java:1194)
	at org.h2.util.JdbcUtils.loadUserClass(JdbcUtils.java:191)
	... 38 common frames omitted
```

**Comment by sdelamo** [comment]
Fixed via https://github.com/micronaut-guides/micronaut-security-jwt/commit/050c7b0d4efbf666b628795f32c51e44dc15b2af
